### ISSUE TITLE
HTML lang attribute to auto-setLocale

### ISSUE THREAD

**Issue by mendrinos** [rmariuzzo/Lang.js#34]
Why to manually enforce the default locale:

Example:
`<script type="text/javascript"> Lang.setLocale('{{App::getLocale()}}'); </script>`

While everyone has the locale defined as an html attribute: lang?

Example:
`<html lang="el">`

It would be great to automatically check the lang attribute of the html tag to preset the default locale.

**Comment by a-komarev** [comment]
I suppose it's related: https://github.com/rmariuzzo/Laravel-JS-Localization/issues/60

**Comment by mendrinos** [comment]
Correct
