### ISSUE TITLE
options is not defined

### ISSUE THREAD

**Issue by okaufmann** [rmariuzzo/Lang.js#48]
Since the newest release I always get this error:

![image](https://user-images.githubusercontent.com/4414498/27997157-7beaf7f2-64f2-11e7-8270-773adccef102.png)

Has anyone an idea?

I'll will check it as soon as i can.

**Comment by rmariuzzo** [comment]
Hey @okaufmann! Can't see the image, can you try to add it again?

**Comment by okaufmann** [comment]
I added it again.

The problem occurs when no locale was set via `Lang.setLocale`.

Maybe this exists for longer than the last release.

**Comment by rmariuzzo** [comment]
I agree, I will have add some test cases and provide a fix, later today or tomorrow. Thanks for taking your time to report this issue.

**Comment by rmariuzzo** [comment]
Actually, I will just add the test case and see if https://github.com/rmariuzzo/Lang.js/pull/46 fixes it.

**Comment by rmariuzzo** [comment]
#46 fixes it, I will release a hot fix soon.
