### ISSUE TITLE
Implement `get` method

### ISSUE THREAD

**Issue by rmariuzzo** [rmariuzzo/Lang.js#5]
## Summary

As a user, I would like to have a `get` method that implement [`Illuminate/Translation/Translator#get`](http://laravel.com/api/5.1/Illuminate/Translation/Translator.html#method_get) method.

## Description

The method should accept 3 arguments: `key`, `replacements` and `locale`. 

 - **`key`** — a string indicating the translation key.
 - **`replace`** — an object of replacements values. Example: `{ key1: 'value1', key2: 'value2' }`.
 - **`locale`** — a string indicating the locale to use. This should be optional, when not set, use `getLocale()`. 

The method will return a localised string for the given key if found, otherwise the given `key`.

## Tests

The `test/spec/lang_get_spec.js` should fully cover all cases of `get` method.

**Comment by gpopoteur** [comment]
@rmariuzzo taking this one as well, as is needed for the `Lang.choice` method.

**Comment by rmariuzzo** [comment]
Cool!
