### ISSUE TITLE
Add documentation about getting a message in a nested directory

### ISSUE THREAD

**Issue by rmariuzzo** [rmariuzzo/Lang.js#51]
We need to add into `README` file a documentation section or note on how to get a message that originally was in a nested directory (that's using the `/`). For example:

```js
Lang.get('forum/thread.hello')
```

The documentation should be added inside the code block here: https://github.com/rmariuzzo/Lang.js#get

**Comment by iCueto** [comment]
I'll do it!

**Comment by rmariuzzo** [comment]
Fixed by #52

**Comment by dewelooper** [comment]
If Im using Lang.get('forum/thread.hello'), JS/VUE convert me this to forum.thread.hello, if I put two slashes gives me two dots ...

If I refer to lang file placed directly in main Laravel lang directory package works perfectly :(
