### ISSUE TITLE
Implement `choice` method

### ISSUE THREAD

**Issue by rmariuzzo** [rmariuzzo/Lang.js#6]
## Summary

As a user, I would like to have a `choice` method that implement [`Illuminate/Translation/Translator#choice`](http://laravel.com/api/5.1/Illuminate/Translation/Translator.html#method_choice) method.

## Description

The method should accept 4 arguments:

 - **`key`** — a string indicating the translation key.
 - **`number`** — a number value indicating something quantifiable.
 - **`replace`** — an object of replacements values. Example: `{ key1: 'value1', key2: 'value2' }`.
 - **`locale`** — a string indicating the locale to use. This should be optional, when not set, use `getLocale()`. 

The method will return a localised string for the given key if found, otherwise the given `key`.

## Tests

The `test/spec/lang_choice_spec.js` should fully cover all cases of `choice` method.

**Comment by gpopoteur** [comment]
@rmariuzzo I'll take this one. :)

**Comment by rmariuzzo** [comment]
Go ahead mate!
