### ISSUE TITLE
Implement `trans` method

### ISSUE THREAD

**Issue by rmariuzzo** [rmariuzzo/Lang.js#7]
## Summary

As a user, I would like to have a `trans` method that implement [`Illuminate/Translation/Translator#trans`](http://laravel.com/api/5.1/Illuminate/Translation/Translator.html#method_trans) method.

## Description

This method should be an _alias_ to `get()` method.

## Tests

The `test/spec/lang_trans_spec.js` should be created and has to fully cover all cases of `trans` method.

**Comment by kamilogorek** [comment]
It should use one reference to the same function, not be created as a separate one. Otherwise it won't be an alias and it will duplicate call stack and eventual error stack trace.

```js
Lang.prototype.get = Lang.prototype.trans = function (key, replacement) { ... }
```

**Comment by rmariuzzo** [comment]
@kamilogorek interesting POV. I agree that both `get` and `has` method should use the same reference.
